// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace AzureConsumptionTracker.Model
{

	public class Tenant
	{

		[JsonProperty("id")]
		public string Id { get; set; }

		[JsonProperty("tenantId")]
		public string TenantId { get; set; }
	}

	public class TenantResponse
	{

		[JsonProperty("value")]
		public Tenant[] TenantCollection { get; set; }
	}

}
